# Generated by Django 6.0.7 on 2026-08-22 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='total_likes',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(default=None, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
